-- TAZC_Babble palette: Indic
-- Indic (Indo-Aryan) family -- a broad, "dynastic" palette. DYNASTIC, NOT CADET:
-- one palette stands in for the Indo-Aryan sphere (Hindi, Urdu, Punjabi, Bengali,
-- ...). Hindi and Urdu are the same spoken language (Hindustani) in two scripts,
-- and a Western ear doesn't split the wider group, so players self-identify their
-- specific language/nation in RP.
--
-- Hindustani (Hindi) is the base. Phonological signature: the aspirated stops
-- (bh/dh/gh/kh/ph/th/jh/chh) that are the unmistakable Indic tell, retroflex
-- consonants, the long vowels aa/ii/uu, nasalization, and the open -aa/-ii/-a
-- (schwa) endings.
--
-- Orthography: ASCII Latin transliteration (common romanization / IAST-lite):
-- aspiration as a trailing h (bh, kh...), retroflex written as plain t/d, sh for
-- the sh sound, long vowels doubled; diacritics dropped. Flattened-transliteration
-- homophones are honest and noted in the forms.

local indic = {
    name   = "Indic",
    family = "indic",

    -- Tuning dials -- see TAZC_Babble.lua header. Open-ish syllables with frequent
    -- -aa/-ii/-a endings; aspirates and long vowels are the featured tells.
    tuning = {
        lettersPerSyllable     = 3,
        onsetChance            = 0.8,
        midCodaChance          = 0.4,
        endingPoolChance       = 0.35,
        functionWordChance     = 0.4,
        elisionPrefixChance    = 0,     -- Indic-specific: no article elision
        signatureBoostWeight   = 2,
        featuredSignatureCount = 1,     -- one tell per utterance so the aspirates/long vowels stay sprinkled
    },

    onsets = {
        "k", "kh", "g", "gh", "ch", "chh", "j", "jh", "t", "th", "d", "dh",
        "n", "p", "ph", "b", "bh", "m", "y", "r", "l", "v", "s", "sh", "h",
    },

    nuclei = {
        -- Schwa 'a' is very common (weighted); the long vowels are the tell.
        "a", "a", "a", "i", "u", "e", "o",
        "aa", "ii", "uu",                            -- long vowels
        "ai", "au",                                  -- diphthongs
    },

    codas = {
        -- Open -aa/-ii/-a endings dominate (empty weighted); -n/-r/-t/-m common.
        "", "", "", "n", "r", "t", "k", "m", "l", "s", "h",
    },

    -- Hesitation fillers (see TAZC_Palette_Turkish for schema docs).
    fillers = {
        "matlab",        -- "matlab: I mean / that is" -- the universal filler
        "yaar",          -- "dude / man" (softener)
        "achha",         -- "achhaa: okay / well / right"
    },

    functionWords = {
        "ka", "ki", "ke", "hai", "aur", "main", "tum", "yeh", "woh", "ek",
        "ko", "se", "me", "par", "na", "bhi", "tha", "hum", "kya", "ye",
    },

    -- Signature set. Aspirated stops on the onset -- the Indic tell -- plus the
    -- long vowels and the -aa/-ii open endings.
    signatureSet = {
        aspirates  = { category = "onset",   elements = {"kh", "gh", "chh", "jh", "th", "dh", "ph", "bh"} },
        longVowels = { category = "nucleus", elements = {"aa", "ii", "uu"} },
        openTail   = { category = "coda",    elements = {"", "", "n"} },   -- keeps -aa/-ii/-an endings frequent
    },

    -- Mishearing rules (babble-resolve). Aspirates de-aspirate, long vowels
    -- shorten. Ordered {from, to}; whole-cluster rules first. DRAFT -- for review.
    -- See docs/BABBLE_RESOLVE.md.
    mishearing = {
        { "chh", "ch" }, { "kh", "k" }, { "gh", "g" }, { "jh", "j" },   -- de-aspirate (chh first)
        { "th", "t" }, { "dh", "d" }, { "ph", "p" }, { "bh", "b" },
        { "aa", "a" }, { "ii", "i" }, { "uu", "u" }, { "sh", "s" },       -- long vowels shorten, sh flattens
    },

    -- Output guard: real Hindi/Urdu vulgarities generated babble must never land
    -- on. Whole-word, lowercase (transliterated). See TAZC_Palette_Turkish for docs.
    babbleBlocklist = {
        "chutiya", "gandu", "lund", "chut", "randi", "harami", "bhosdi", "madarchod",
    },

    -- ====================================================================
    -- INTEGRATION-LAYER DATA (optional, ignored by TAZC_Babble engine)
    -- ====================================================================

    -- concept-keyed lex sourced from data/forms.tsv (the indic column) via
    -- devtools/generate_palette_forms.py. Hindustani (Hindi), transliterated:
    -- verbs in the -na infinitive; nouns singular; adjectives masculine singular.
    -- DRAFTS pending native-speaker review (flagged in the TSV note column).
    lex = require("TAZC_PaletteFormsData").indic,

    -- Zipf frequency order. Generated by devtools/generate_rankings.py; Indic
    -- never shipped, so all forms ride the baseline-less English-frequency path.
    -- Regenerate after editing forms.tsv; do NOT hand-edit.
    zipf = {
        -- GENERATED by devtools/generate_rankings.py -- do NOT hand-edit.
        -- Order: frozen 8.16.1 baseline + frequency-anchored insertions
        -- (see generator docstring). Regenerate after editing forms.tsv.
        -- Rank 1-10
        "andar", "main", "vah", "tum", "yah", "na", "hum", "sab", "ve", "ek",
        -- Rank 11-20
        "dibba", "upar", "baahar", "kya", "kab", "nahin", "kaun", "naya", "kaise", "abhi",
        -- Rank 21-30
        "doosra", "achchha", "baad", "pehla", "jaanna", "dekhna", "do", "banaana", "sochna", "tab",
        -- Rank 31-40
        "peeth", "chaahna", "jaana", "theek", "kahaan", "zaroorat", "daayaan", "kaam", "saal", "din",
        -- Rank 41-50
        "pehle", "kyun", "lena", "bahut", "kahna", "niiche", "pyaar", "mard", "ghar", "lamba",
        -- Rank 51-60
        "dekhna", "kuch", "istemaal", "samaan", "aana", "tiin", "paana", "madad", "puraana", "khel",
        -- Rank 61-70
        "dena", "ghar", "dobara", "dikhaana", "bada", "rakhna", "rishtedaar", "kripaya", "koi", "baayaan",
        -- Rank 71-80
        "naam", "raat", "khelna", "thoda", "alag", "upar", "shuru", "hafta", "kuchbhi", "aadmi",
        -- Rank 81-90
        "aaj", "sabkuch", "bhara", "jeena", "padhna", "bura", "chaar", "sakht", "bataana", "rukna",
        -- Rank 91-100
        "paani", "sir", "chhota", "safed", "duur", "kaam", "taraf", "aazmaana", "haan", "bhaagna",
        -- Rank 101-110
        "kholna", "mausam", "shukriya", "kaala", "gaadi", "chehra", "paanch", "shaayad", "kahaani", "ummiid",
        -- Rank 111-120
        "zaroori", "kitaab", "jaldi", "jawaan", "aadha", "haath", "shareer", "khaana", "dakshin", "kamra",
        -- Rank 121-130
        "jiitna", "galat", "dost", "maarna", "samajhna", "hilna", "thaharna", "aurat", "poochhna", "der",
        -- Rank 131-140
        "uttar", "aari", "roshni", "halka", "subah", "rahna", "laal", "jald", "dil", "bachcha",
        -- Rank 141-150
        "aag", "peechhe", "imaarat", "aasaan", "paas", "yojana", "chhah", "pashchim", "saamne", "taiyaar",
        -- Rank 151-160
        "beta", "laana", "milna", "shishu", "pita", "gaana", "maheena", "kaatna", "khet", "maa",
        -- Rank 161-170
        "sadak", "shahar", "ladna", "sunna", "daam", "aaraam", "garmi", "patni", "mazboot", "danda",
        -- Rank 171-180
        "baantna", "mara", "hona", "pakadna", "taara", "todna", "ghanta", "beech", "maafi", "jawaab",
        -- Rank 181-190
        "siikhna", "akela", "girja", "puurab", "garam", "khada", "neela", "chalaana", "khaana", "girna",
        -- Rank 191-200
        "tez", "hara", "bharosa", "chaabi", "vyaapaar", "bhai", "pyaala", "nafrat", "bhejna", "khoon",
        -- Rank 201-210
        "kutta", "tel", "maarna", "gareeb", "dhakna", "darvaaza", "baal", "khona", "saat", "saral",
        -- Rank 211-220
        "chalna", "betii", "marna", "kaagaz", "surakshit", "zameen", "bhuulna", "samundar", "sona", "das",
        -- Rank 221-230
        "dabba", "banana", "andhera", "deewaar", "dard", "nadi", "bolna", "likhna", "thanda", "aath",
        -- Rank 231-240
        "aankh", "shaanti", "sanjona", "kal", "bhuura", "radio", "pati", "baraf", "saaf", "suuraj",
        -- Rank 241-250
        "banduuk", "bhaari", "dhuundhna", "dar", "neta", "chitthi", "saamaan", "bahan", "dimaag", "farsh",
        -- Rank 251-260
        "basant", "pehanna", "sapna", "khatam", "kismat", "ameer", "tvacha", "chhuuna", "kal", "piina",
        -- Rank 261-270
        "machhli", "badhna", "baithna", "dhona", "paudha", "sardi", "biimaar", "pakadna", "paanv", "nau",
        -- Rank 271-280
        "kofi", "shaam", "kaanch", "dhiima", "ped", "neeche", "injan", "letna", "udaasi", "hawa",
        -- Rank 281-290
        "chinta", "ginna", "jhiil", "munh", "phenkna", "dhaatu", "khinchna", "dhakelna", "jaanvar", "ghusna",
        -- Rank 291-300
        "patthar", "khidki", "thaila", "dera", "billi", "faisla", "tohfa", "lakdi", "pul", "bagiicha",
        -- Rank 301-310
        "zinda", "ghoda", "naksha", "jaal", "vaahan", "jaagna", "kona", "khet", "sudharna", "udna",
        -- Rank 311-320
        "hairaani", "suukha", "kinaara", "chot", "baazu", "dawaa", "pahaad", "chakhna", "chai", "iindhan",
        -- Rank 321-330
        "namaste", "aasmaan", "naav", "sau", "raasta", "vaada", "baarish", "thaka", "dushman", "jangal",
        -- Rank 331-340
        "chaand", "kuudna", "peela", "naram", "dhuaan", "sikhaana", "chhed", "taang", "doodh", "barf",
        -- Rank 341-350
        "kamzor", "zanjiir", "pakaana", "rasoi", "shaant", "ajeeb", "trak", "chidiya", "katora", "murgi",
        -- Rank 351-360
        "gosht", "gardan", "kamiiz", "naarangi", "sharaab", "namak", "saavdhaan", "khatra", "khaalii", "mehmaan",
        -- Rank 361-370
        "botal", "paniir", "phal", "auzaar", "ganda", "khushi", "shor", "thaali", "raahat", "chaawal",
        -- Rank 371-380
        "chhat", "sharam", "shaant", "chhupna", "hathiyaar", "geela", "jalaana", "topi", "tez", "chhaati",
        -- Rank 381-390
        "gulaabi", "taala", "naak", "plaastik", "baandhna", "roti", "uthana", "kandha", "pahiya", "jhaadi",
        -- Rank 391-400
        "shikaar", "suunghna", "ungli", "sleti", "tez", "haddi", "poshaak", "phaatak", "baadal", "anda",
        -- Rank 401-410
        "dhona", "bhuukha", "chacha", "ret", "dhaaga", "ghadi", "kaan", "gussa", "kamarband", "phuul",
        -- Rank 411-420
        "pet", "dhuul", "chaaku", "jad", "churaana", "patila", "tava", "ghaas", "shahad", "kaanta",
        -- Rank 421-430
        "biij", "talwaar", "jiibh", "kot", "ras", "stan", "nikalna", "chamda", "bhediya", "sankraman",
        -- Rank 431-440
        "ghutna", "phanda", "baingani", "kaatna", "mukhauta", "dhanush", "alvida", "dhaal", "gala", "ajnabi",
        -- Rank 441-450
        "kharpatwaar", "patjhad", "goli", "batorna", "daada", "juuta", "ghaav", "hatheli", "rabar", "saanp",
        -- Rank 451-460
        "chadhna", "khodna", "bukhaar", "patta", "baada", "naakhun", "keel", "tairna", "gufaa", "maans",
        -- Rank 461-470
        "boot", "uljhan", "bhed", "anaaj", "peepa", "chuuha", "raakh", "chaachi", "hathauda", "fasal",
        -- Rank 471-480
        "shorba", "gaay", "daadi", "suar", "siidhi", "teer", "honth", "keechad", "hiran", "bharna",
        -- Rank 481-490
        "dopahar", "pet", "phephda", "shok", "zahar", "daant", "tokri", "kambal", "baalti", "ungli",
        -- Rank 491-500
        "rassi", "chillaana", "diya", "meva", "kapda", "bartan", "kaanta", "kaatna", "siidhi", "bhatija",
        -- Rank 501-510
        "anguutha", "kalaai", "thodi", "saikil", "jabda", "sui", "takhna", "ber", "gaal", "bhothra",
        -- Rank 511-520
        "sabzi", "martaban", "bora", "mombatti", "chammach", "maatha", "kohnii", "edi", "bhatiji", "kulhaadi",
        -- Rank 521-530
        "nishaan", "kiida", "pyaasa", "mashaal", "dastaana", "bhaala", "patloon", "peya", "padosi", "akelaapan",
        -- Rank 531-539
        "khumbi", "ghin", "moza", "pasli", "belcha", "bona", "patti", "niil", "naabhi",
    },

    -- ========================================================================
    -- CULTURAL BLOCK -- see TAZC_Palette_French for full schema docs. Transliterated;
    -- multi-word l2 phrases are fine (the cultural pass substitutes whole phrases).
    -- ========================================================================
    cultural = {
        { en = "Greetings, I bow to you respectfully",  l2 = "namaste",             tags = {"greeting"} },
        { en = "It is no problem at all, never mind",   l2 = "koi baat nahi",       tags = {} },
        { en = "Everything is fine, all is well",       l2 = "sab theek hai",       tags = {} },
        { en = "By the grace of God, God willing",      l2 = "bhagwan ki kripa",    tags = {"modal"} },
        { en = "Come on then, let us get going",        l2 = "chalo",               tags = {"action"} },
        { en = "Eat well and be content, my friend",    l2 = "khaao piyo",          tags = {"meal"} },
    },
}

-- Self-register with the language system.
require("TAZC_LangRegistry").register("indic", indic)

return indic
