-- TAZC_Babble palette: Semitic
-- Semitic family -- a broad, "dynastic" palette. DYNASTIC, NOT CADET: one palette
-- stands in for the Semitic branch (Arabic dialects -- Egyptian/Levantine/Gulf/
-- Maghrebi -- and loosely Hebrew). A Western ear doesn't reliably split them, so
-- players who want to voice a specific variety use this palette and self-identify
-- their nation in RP.
--
-- Modern Standard Arabic is the base. Phonological signature: the definite-
-- article prefix al-/el-, the gutturals kh/gh/q/h, emphatic sibilants (sh/th/dh),
-- the tight three-vowel system (a/i/u, long aa/ii/uu -- NO e/o), consonant-framed
-- CVC roots, and the -a/-at feminine endings.
--
-- Orthography: ASCII Latin transliteration (like the Slavic palette's Russian):
-- kh/gh/sh/th/dh digraphs, q for qaf, long vowels doubled; ayn and hamza are
-- dropped (no apostrophes). Homophones from the flattened transliteration are
-- honest and noted in the forms.

local semitic = {
    name   = "Semitic",
    family = "semitic",

    -- Tuning dials -- see TAZC_Babble.lua header. Consonant-framed (moderate coda
    -- rate), and the al-/el- article rides in as an elision prefix ~1/3 of words.
    tuning = {
        lettersPerSyllable     = 3,
        onsetChance            = 0.85,
        midCodaChance          = 0.45,
        endingPoolChance       = 0.4,
        functionWordChance     = 0.4,
        elisionPrefixChance    = 0.3,   -- the al-/el- definite article
        signatureBoostWeight   = 2,
        featuredSignatureCount = 1,     -- one tell per utterance so long vowels/gutturals don't pile up
    },

    onsets = {
        "b", "t", "th", "j", "h", "kh", "d", "dh", "r", "z", "s", "sh",
        "q", "k", "l", "m", "n", "f", "gh", "w", "y",
    },

    nuclei = {
        -- The Arabic three-vowel system: a/i/u only (no e/o), each also long.
        "a", "a", "a", "i", "i", "u", "u",
        "aa", "ii", "uu",                            -- long vowels (the tell)
        "ay", "aw",                                  -- diphthongs (bayt, yawm)
    },

    codas = {
        -- Consonant-framed; -a / -at are the feminine (ta-marbuta) endings.
        "", "", "b", "t", "n", "r", "m", "l", "s", "q", "d", "sh", "h", "a", "at",
    },

    elisionPrefixes = {
        -- The definite article -- the single most recognisable Arabic tell.
        "al", "el", "il",
    },

    -- Hesitation fillers (see TAZC_Palette_Turkish for schema docs).
    fillers = {
        "yaani",         -- "yaʿni: I mean / that is" -- the universal filler
        "wallah",        -- "I swear / honestly"
        "yalla",         -- "come on / let's go" (softener)
    },

    functionWords = {
        "al", "fi", "min", "ila", "ala", "wa", "la", "ma", "an",
        "huwa", "hiya", "hatha", "kull", "ya", "fa", "bi", "li", "huna",
    },

    -- Signature set. Gutturals + emphatics on the onset, long vowels on the
    -- nucleus, the feminine -a/-at on the coda.
    signatureSet = {
        gutturals  = { category = "onset",   elements = {"kh", "gh", "q", "h"} },
        emphatics  = { category = "onset",   elements = {"sh", "th", "dh", "s"} },
        longVowels = { category = "nucleus", elements = {"aa", "ii", "uu"} },
        femEndings = { category = "coda",    elements = {"a", "at", "ah"} },
    },

    -- Mishearing rules (babble-resolve). Gutturals flatten, long vowels shorten,
    -- the article reduces. DRAFT -- for review. See docs/BABBLE_RESOLVE.md.
    mishearing = {
        { "kh", "k" }, { "gh", "g" }, { "th", "t" }, { "dh", "d" }, { "sh", "s" },  -- gutturals/emphatics
        { "aa", "a" }, { "ii", "i" }, { "uu", "u" },                                 -- long vowels shorten
        { "q", "k" }, { "al", "a" },                                                 -- qaf -> k, article reduces
    },

    -- Output guard: real Arabic vulgarities generated babble must never land on.
    -- Whole-word, lowercase (transliterated). See TAZC_Palette_Turkish for docs.
    babbleBlocklist = {
        "khara", "kus", "zubr", "nik", "sharmuta", "gahba", "ayre", "khawal",
    },

    -- ====================================================================
    -- INTEGRATION-LAYER DATA (optional, ignored by TAZC_Babble engine)
    -- ====================================================================

    -- concept-keyed lex sourced from data/forms.tsv (the semitic column) via
    -- devtools/generate_palette_forms.py. Modern Standard Arabic, transliterated:
    -- verbs in the 3rd-masc-singular past / dictionary root form; nouns singular;
    -- adjectives masculine singular. DRAFTS pending native-speaker review -- Arabic
    -- morphology and transliteration are especially review-hungry.
    lex = require("TAZC_PaletteFormsData").semitic,

    -- Zipf frequency order. Generated by devtools/generate_rankings.py; Semitic
    -- never shipped, so all forms ride the baseline-less English-frequency path.
    -- Regenerate after editing forms.tsv; do NOT hand-edit.
    zipf = {
        -- GENERATED by devtools/generate_rankings.py -- do NOT hand-edit.
        -- Order: frozen 8.16.1 baseline + frequency-anchored insertions
        -- (see generator docstring). Regenerate after editing forms.tsv.
        -- Rank 1-10
        "fii", "ana", "dhalika", "anta", "hadha", "laa", "nahnu", "kull", "hum", "waahid",
        -- Rank 11-20
        "ulba", "fawq", "khaarij", "maadha", "mataa", "laa", "man", "jadiid", "kayf", "aan",
        -- Rank 21-30
        "aakhar", "jayyid", "baad", "awwal", "arafa", "raa", "ithnaan", "sanaa", "fakkara", "thumma",
        -- Rank 31-40
        "zahr", "araada", "dhahaba", "saliim", "ayna", "ihtaaja", "yamiin", "amila", "sana", "nahaar",
        -- Rank 41-50
        "qabl", "limaadha", "akhadha", "kathiir", "qaala", "taht", "hubb", "rajul", "dar", "tawiil",
        -- Rank 51-60
        "nazara", "shay", "istakhdama", "nafs", "jaa", "thalatha", "wajada", "musaada", "qadiim", "luba",
        -- Rank 61-70
        "aata", "bayt", "mujaddadan", "araa", "kabiir", "shaara", "hafiza", "ahl", "rajaa", "ahad",
        -- Rank 71-80
        "yasaar", "ism", "layl", "laiba", "qaliil", "mukhtalif", "qimma", "badaa", "usbuu", "shakhs",
        -- Rank 81-90
        "yawm", "malaan", "aasha", "qaraa", "sayyi", "arbaa", "sulb", "akhbara", "waqafa", "maa",
        -- Rank 91-100
        "raas", "saghiir", "abyad", "baiid", "waziifa", "jaanib", "haawala", "naam", "jaraa", "fataha",
        -- Rank 101-110
        "fasl", "shukran", "aswad", "sayyaara", "wajh", "khamsa", "rubbama", "qissa", "amal", "muhimm",
        -- Rank 111-120
        "kitaab", "mubakkir", "shaab", "nisf", "yad", "jasad", "taam", "januub", "ghurfa", "faaza",
        -- Rank 121-130
        "khata", "tadhakkara", "sadiq", "daraba", "fahima", "aghlaqa", "taharraka", "intazara", "imraa", "saala",
        -- Rank 131-140
        "mutaakhkhir", "shamaal", "minshaar", "nuur", "khafiif", "sabaah", "baqiya", "ahmar", "qariiban", "qalb",
        -- Rank 141-150
        "tifl", "naar", "khalf", "mabnaa", "sahl", "qariib", "khitta", "sitta", "gharb", "amam",
        -- Rank 151-160
        "jaahiz", "ibn", "ahdara", "qaabala", "radii", "ab", "ughniya", "shahr", "qataa", "haql",
        -- Rank 161-170
        "umm", "tariiq", "balda", "qaatala", "samia", "thaman", "istaraaha", "sayf", "zawja", "qawii",
        -- Rank 171-180
        "hiraawa", "shaaraka", "mayyit", "hadatha", "amsaka", "najm", "kasara", "saa", "wasat", "aasif",
        -- Rank 181-190
        "ajaaba", "taallama", "wahiid", "kaniisa", "sharq", "haarr", "tabia", "qaama", "azraq", "saaqa",
        -- Rank 191-200
        "akala", "saqata", "sarii", "akhdar", "thiqa", "miftaah", "taajara", "akh", "kuub", "karaahiya",
        -- Rank 201-210
        "arsala", "dam", "kalb", "zayt", "qatala", "faqiir", "ghattaa", "baab", "shar", "faqada",
        -- Rank 211-220
        "sabaa", "basiit", "mashaa", "bint", "maata", "waraq", "aamin", "ard", "nasiya", "bahr",
        -- Rank 221-230
        "naama", "ashara", "sunduuq", "banaa", "zalaam", "jidaar", "alam", "nahr", "takallama", "kataba",
        -- Rank 231-240
        "baarid", "thamaaniya", "ayn", "salaam", "khazana", "ghadan", "bunni", "raadyo", "zawj", "jaliid",
        -- Rank 241-250
        "naziif", "shams", "bunduqiyya", "thaqiil", "bahatha", "khawf", "zaiim", "risaala", "maadda", "ukht",
        -- Rank 251-260
        "dimaagh", "ardiyya", "rabii", "labisa", "hulm", "anha", "hazz", "ghanii", "jild", "lamasa",
        -- Rank 261-270
        "ams", "shariba", "samak", "namaa", "jalasa", "hamala", "nabaat", "shitaa", "mariid", "amsaka",
        -- Rank 271-280
        "qadam", "tisa", "qahwa", "masaa", "zujaj", "batii", "shajara", "asfal", "muharrik", "istalqa",
        -- Rank 281-290
        "huzn", "riih", "qaliqa", "adda", "buhayra", "fam", "rama", "madin", "sahaba", "dafaa",
        -- Rank 291-300
        "hayawaan", "dakhala", "hajar", "naafidha", "kiis", "mukhayyam", "qitt", "qarrara", "hadiyya", "khashab",
        -- Rank 301-310
        "jisr", "hadiiqa", "hayy", "hisaan", "khariita", "shabaka", "markaba", "istayqaza", "rukn", "mazraa",
        -- Rank 311-320
        "aslaha", "taara", "dahsha", "jaaff", "haaffa", "isaaba", "dhiraa", "dawaa", "jabal", "atlaqa",
        -- Rank 321-330
        "dhaaqa", "shaay", "waqud", "marhaba", "samaa", "qaarib", "mia", "darb", "waada", "matar",
        -- Rank 331-340
        "taban", "aduww", "ghaba", "qamar", "qafaza", "asfar", "layyin", "dukhaan", "allama", "hufra",
        -- Rank 341-350
        "saaq", "haliib", "thalj", "daiif", "silsila", "tabakha", "matbakh", "haadi", "ghariib", "shaahina",
        -- Rank 351-360
        "tayr", "zubdiyya", "dajaaja", "lahm", "raqaba", "qamiis", "burtuqaali", "kuhuul", "milh", "hadhir",
        -- Rank 361-370
        "khatar", "faarigh", "dayf", "zujaaja", "jubn", "fakiha", "adaa", "wasikh", "farah", "dajiij",
        -- Rank 371-380
        "sahn", "irtiyaah", "ruzz", "saqf", "khajal", "haadi", "ikhtaba", "silaah", "mubtall", "haraqa",
        -- Rank 381-390
        "qubbaa", "saakhib", "sadr", "wardii", "qufl", "anf", "blastik", "rabata", "khubz", "rafaa",
        -- Rank 391-400
        "katif", "ajala", "shujayra", "saada", "shamma", "isba", "ramadi", "haadd", "azm", "libaas",
        -- Rank 401-410
        "bawwaba", "ghayma", "bayda", "ghasala", "jawaan", "amm", "raml", "khayt", "saa", "udhun",
        -- Rank 411-420
        "ghadab", "hizaam", "zahra", "maida", "ghubaar", "sikkiin", "jidhr", "saraqa", "qidr", "miqlaah",
        -- Rank 421-430
        "ushb", "asal", "khuttaaf", "badhra", "sayf", "lisaan", "mitaf", "asiir", "thady", "kharaja",
        -- Rank 431-440
        "jild", "dhib", "adwa", "rukba", "misyada", "banafsajii", "adda", "kimaama", "qaws", "turs",
        -- Rank 441-450
        "halq", "gharib", "ushba", "khariif", "tanaffasa", "rasaasa", "jamaa", "jadd", "hidhaa", "jurh",
        -- Rank 451-460
        "kaff", "mattaat", "hayya", "tasallaqa", "hafara", "humma", "waraqa", "siyaaj", "zufr", "mismaar",
        -- Rank 461-470
        "sabaha", "kahf", "lahm", "jazma", "irtibaak", "kharuuf", "habb", "barmiil", "juradh", "ramaad",
        -- Rank 471-480
        "khaala", "mitraqa", "mahsuul", "shuurba", "baqara", "jadda", "khinziir", "daraj", "sahm", "shafa",
        -- Rank 481-490
        "tiin", "ayyil", "shafa", "dhuhr", "batn", "ria", "huzn", "samm", "sinn", "salla",
        -- Rank 491-500
        "battaniyya", "dalw", "isba", "habl", "sarakha", "misbaah", "jawz", "qumaash", "haawiya", "shawka",
        -- Rank 501-510
        "hasada", "sullam", "ibhaam", "rusgh", "dhaqn", "darraaja", "fakk", "ibra", "kaahil", "tuut",
        -- Rank 511-520
        "khadd", "kaliil", "khudaar", "jarra", "kiis", "shama", "milaqa", "jabha", "mirfaq", "kab",
        -- Rank 521-530
        "faas", "nadba", "hashara", "atshan", "mishal", "quffaz", "nazafa", "rumh", "bantaloon", "mashruub",
        -- Rank 531-540
        "jaar", "wahda", "fitr", "qaraf", "akh", "jawrab", "dila", "mijrafa", "zaraa", "dimaad",
        -- Rank 541-542
        "kadma", "surra",
    },

    -- ========================================================================
    -- CULTURAL BLOCK -- see TAZC_Palette_French for full schema docs. Transliterated;
    -- multi-word l2 phrases are fine (the cultural pass substitutes whole phrases).
    -- ========================================================================
    cultural = {
        { en = "God willing, if it is meant to be",     l2 = "inshallah",         tags = {"modal"} },
        { en = "Thank God, all praise is due",          l2 = "alhamdulillah",     tags = {} },
        { en = "Peace be upon you, greetings friend",   l2 = "salaam alaykum",    tags = {"greeting"} },
        { en = "Go in peace, farewell for now",         l2 = "maa salama",        tags = {"farewell"} },
        { en = "In the name of God, let us begin",      l2 = "bismillah",         tags = {} },
        { en = "That is enough, it is finished",        l2 = "khalas",            tags = {} },
    },
}

-- Self-register with the language system.
require("TAZC_LangRegistry").register("semitic", semitic)

return semitic
