-- TAZC_Babble palette: Bantu
-- Niger-Congo / Bantu family -- a broad, "dynastic" palette, and the mod's first
-- sub-Saharan African language. DYNASTIC, NOT CADET: one palette stands in for
-- the Bantu branch (Swahili, Zulu, Lingala, Kikuyu, Shona...); a Western ear
-- doesn't split them, so players self-identify their specific language in RP.
--
-- Swahili is the base. Phonological signature: strictly open CV syllables (every
-- syllable ends in a vowel, five pure vowels a/e/i/o/u), the prenasalized stops
-- mb/nd/ng/nj/nz that are the unmistakable Bantu tell, the mw-/ny- onsets, and
-- the -a verb endings.
--
-- Orthography: standard Swahili spelling, which is already Latin and phonetic --
-- ASCII-clean, no transliteration or byte-escaping needed.

local bantu = {
    name   = "Bantu",
    family = "bantu",

    -- Tuning dials -- see TAZC_Babble.lua header. Open CV throughout: onsets almost
    -- always present, codas empty (every syllable ends in a vowel), short words.
    tuning = {
        lettersPerSyllable     = 2,     -- open CV morae, like Japonic
        onsetChance            = 0.9,
        midCodaChance          = 0.0,   -- no codas: Bantu syllables are open
        endingPoolChance       = 0.0,
        functionWordChance     = 0.4,
        elisionPrefixChance    = 0,
        signatureBoostWeight   = 2,
        featuredSignatureCount = 1,
    },

    onsets = {
        "b", "ch", "d", "f", "g", "h", "j", "k", "l", "m", "n", "p", "r",
        "s", "t", "v", "w", "y", "z", "sh",
        "mb", "nd", "ng", "nj", "nz",                -- prenasalized (the Bantu tell)
        "mw", "ny", "kw", "gw",                       -- labialized / palatal onsets
    },

    nuclei = {
        -- Five pure vowels; -a is weighted (the common verb / noun ending).
        "a", "a", "a", "e", "e", "i", "i", "o", "o", "u", "u",
    },

    codas = {
        -- Empty: Bantu syllables are open, every word ends in a vowel.
        "",
    },

    functionWords = {
        -- Swahili connectives / concords / demonstratives.
        "na", "wa", "ya", "za", "la", "kwa", "ni", "si", "au", "kila",
        "huyu", "hii", "yeye", "mimi", "wewe", "sisi", "ndani", "kwenye",
    },

    -- Hesitation fillers (see TAZC_Palette_Turkish for schema docs).
    fillers = {
        "yaani",         -- "yaani: I mean / that is" -- the universal filler
        "basi",          -- "basi: so / well then"
        "kumbe",         -- "kumbe: well / as it turns out"
    },

    -- Signature set. The prenasalized stops and mw-/ny- onsets are the tell; the
    -- open CV / vowel endings are structural (codas are empty).
    signatureSet = {
        prenasalized  = { category = "onset", elements = {"mb", "nd", "ng", "nj", "nz"} },
        labialPalatal = { category = "onset", elements = {"mw", "ny", "kw", "gw"} },
    },

    -- Mishearing rules (babble-resolve). Prenasalized stops lose the nasal, the
    -- labialized onsets simplify. DRAFT -- for review. See docs/BABBLE_RESOLVE.md.
    mishearing = {
        { "mb", "b" }, { "nd", "d" }, { "ng", "g" }, { "nj", "j" }, { "nz", "z" },  -- de-nasalise
        { "mw", "m" }, { "ny", "n" }, { "kw", "k" }, { "gw", "g" },                  -- de-labialise
        { "sh", "s" },
    },

    -- Output guard: real Swahili vulgarities generated babble must never land on.
    -- Whole-word, lowercase. See TAZC_Palette_Turkish for docs.
    babbleBlocklist = {
        "kuma", "mboo", "mavi", "malaya", "shenzi", "kumamayo", "matako",
    },

    -- ====================================================================
    -- INTEGRATION-LAYER DATA (optional, ignored by TAZC_Babble engine)
    -- ====================================================================

    -- concept-keyed lex sourced from data/forms.tsv (the bantu column) via
    -- devtools/generate_palette_forms.py. Standard Swahili: verbs in the ku-
    -- infinitive or bare stem; nouns keep their class prefix; adjectives base.
    -- DRAFTS pending native-speaker review (flagged in the TSV note column).
    lex = require("TAZC_PaletteFormsData").bantu,

    -- Zipf frequency order. Generated by devtools/generate_rankings.py; Bantu
    -- never shipped, so all forms ride the baseline-less English-frequency path.
    -- Regenerate after editing forms.tsv; do NOT hand-edit.
    zipf = {
        -- GENERATED by devtools/generate_rankings.py -- do NOT hand-edit.
        -- Order: frozen 8.16.1 baseline + frequency-anchored insertions
        -- (see generator docstring). Regenerate after editing forms.tsv.
        -- Rank 1-10
        "ndani", "mimi", "ile", "wewe", "hii", "si", "sisi", "wote", "wao", "moja",
        -- Rank 11-20
        "kopo", "juu", "nje", "nini", "lini", "hapana", "nani", "pya", "vipi", "sasa",
        -- Rank 21-30
        "ingine", "zuri", "baada", "kwanza", "jua", "ona", "mbili", "tengeneza", "fikiri", "kisha",
        -- Rank 31-40
        "mgongo", "taka", "kwenda", "mzima", "wapi", "hitaji", "kulia", "kazi", "mwaka", "mchana",
        -- Rank 41-50
        "kabla", "mbona", "chukua", "ingi", "sema", "chini", "upendo", "mwanamume", "nyumbani", "refu",
        -- Rank 51-60
        "tazama", "kitu", "tumia", "sawa", "kuja", "tatu", "pata", "msaada", "zee", "mchezo",
        -- Rank 61-70
        "kupa", "nyumba", "tena", "onyesha", "kubwa", "hisi", "weka", "jamaa", "tafadhali", "mtu",
        -- Rank 71-80
        "kushoto", "jina", "usiku", "cheza", "chache", "tofauti", "juu", "anza", "wiki", "chochote",
        -- Rank 81-90
        "mtu", "leo", "jaa", "ishi", "soma", "mbaya", "nne", "gumu", "ambia", "acha",
        -- Rank 91-100
        "maji", "kichwa", "dogo", "nyeupe", "mbali", "kazi", "upande", "jaribu", "ndiyo", "kimbia",
        -- Rank 101-110
        "fungua", "msimu", "asante", "nyeusi", "gari", "uso", "tano", "labda", "hadithi", "tumaini",
        -- Rank 111-120
        "muhimu", "kitabu", "mapema", "changa", "nusu", "mkono", "mwili", "chakula", "kusini", "chumba",
        -- Rank 121-130
        "shinda", "kosa", "kumbuka", "rafiki", "piga", "elewa", "funga", "sogea", "ngoja", "mwanamke",
        -- Rank 131-140
        "uliza", "kuchelewa", "kaskazini", "msumeno", "mwanga", "epesi", "asubuhi", "kaa", "nyekundu", "punde",
        -- Rank 141-150
        "moyo", "mtoto", "moto", "nyuma", "jengo", "rahisi", "karibu", "mpango", "sita", "magharibi",
        -- Rank 151-160
        "mbele", "tayari", "mwana", "leta", "kutana", "kichanga", "baba", "wimbo", "mwezi", "kata",
        -- Rank 161-170
        "shamba", "mama", "barabara", "mji", "pigana", "sikia", "bei", "pumzika", "kiangazi", "mke",
        -- Rank 171-180
        "imara", "rungu", "gawa", "mfu", "tokea", "shika", "nyota", "vunja", "saa", "katikati",
        -- Rank 181-190
        "samahani", "jibu", "jifunza", "peke", "kanisa", "mashariki", "joto", "fuata", "simama", "bluu",
        -- Rank 191-200
        "endesha", "kula", "anguka", "haraka", "kijani", "imani", "ufunguo", "biashara", "kaka", "kikombe",
        -- Rank 201-210
        "chukia", "tuma", "damu", "mbwa", "mafuta", "ua", "maskini", "funika", "mlango", "nywele",
        -- Rank 211-220
        "poteza", "saba", "sahili", "tembea", "binti", "kufa", "karatasi", "salama", "udongo", "sahau",
        -- Rank 221-230
        "bahari", "lala", "kumi", "sanduku", "jenga", "giza", "ukuta", "maumivu", "mto", "ongea",
        -- Rank 231-240
        "andika", "baridi", "nane", "jicho", "amani", "hifadhi", "kesho", "kahawia", "redio", "mume",
        -- Rank 241-250
        "barafu", "safi", "jua", "bunduki", "zito", "tafuta", "hofu", "kiongozi", "barua", "malighafi",
        -- Rank 251-260
        "dada", "ubongo", "sakafu", "hakuna", "masika", "vaa", "ndoto", "maliza", "bahati", "tajiri",
        -- Rank 261-270
        "ngozi", "gusa", "jana", "kunywa", "samaki", "kua", "kaa", "beba", "mmea", "kipupwe",
        -- Rank 271-280
        "mgonjwa", "kamata", "mguu", "tisa", "kahawa", "jioni", "kioo", "polepole", "mti", "chini",
        -- Rank 281-290
        "injini", "lala", "huzuni", "upepo", "wasiwasi", "hesabu", "ziwa", "kinywa", "tupa", "chuma",
        -- Rank 291-300
        "vuta", "sukuma", "mnyama", "ingia", "jiwe", "dirisha", "mfuko", "kambi", "paka", "amua",
        -- Rank 301-310
        "zawadi", "mbao", "daraja", "bustani", "hai", "farasi", "ramani", "wavu", "gari", "amka",
        -- Rank 311-320
        "pembe", "shamba", "tengeneza", "ruka", "mshangao", "kavu", "ukingo", "jeraha", "mkono", "dawa",
        -- Rank 321-330
        "mlima", "fyatua", "onja", "chai", "mafuta", "jambo", "anga", "mashua", "mia", "njia",
        -- Rank 331-340
        "ahidi", "mvua", "choka", "adui", "msitu", "mwezi", "ruka", "njano", "laini", "moshi",
        -- Rank 341-350
        "fundisha", "shimo", "mguu", "maziwa", "theluji", "dhaifu", "mnyororo", "pika", "jikoni", "kimya",
        -- Rank 351-360
        "geni", "lori", "ndege", "bakuli", "kuku", "nyama", "shingo", "shati", "chungwa", "pombe",
        -- Rank 361-370
        "chumvi", "makini", "hatari", "tupu", "mgeni", "chupa", "jibini", "tunda", "kifaa", "chafu",
        -- Rank 371-380
        "furaha", "kelele", "sahani", "faraja", "mchele", "paa", "aibu", "tulivu", "jificha", "silaha",
        -- Rank 381-390
        "chepechepe", "choma", "kofia", "kifua", "waridi", "kufuli", "pua", "plastiki", "funga", "mkate",
        -- Rank 391-400
        "inua", "bega", "gurudumu", "kichaka", "winda", "nusa", "kidole", "kijivu", "kali", "mfupa",
        -- Rank 401-410
        "nguo", "lango", "wingu", "yai", "osha", "njaa", "mjomba", "mchanga", "uzi", "saa",
        -- Rank 411-420
        "sikio", "hasira", "mkanda", "ua", "tumbo", "binamu", "vumbi", "kisu", "mzizi", "iba",
        -- Rank 421-430
        "sufuria", "kikaango", "nyasi", "asali", "ndoana", "mbegu", "upanga", "ulimi", "koti", "juisi",
        -- Rank 431-440
        "titi", "toka", "ngozi", "maambukizi", "goti", "mtego", "zambarau", "uma", "barakoa", "manane",
        -- Rank 441-450
        "upinde", "kwaheri", "ngao", "koo", "mgeni", "gugu", "vuli", "pumua", "risasi", "kusanya",
        -- Rank 451-460
        "babu", "kiatu", "jeraha", "kiganja", "mpira", "nyoka", "panda", "chimba", "homa", "jani",
        -- Rank 461-470
        "uzio", "ukucha", "msumari", "ogelea", "pango", "nyama", "buti", "mkanganyiko", "kondoo", "nafaka",
        -- Rank 471-480
        "pipa", "panya", "jivu", "shangazi", "nyundo", "zao", "supu", "ngombe", "bibi", "nguruwe",
        -- Rank 481-490
        "ngazi", "mshale", "mdomo", "matope", "paa", "pona", "adhuhuri", "tumbo", "pafu", "majonzi",
        -- Rank 491-500
        "sumu", "jino", "kikapu", "blanketi", "ndoo", "kamba", "taa", "kokwa", "kitambaa", "chombo",
        -- Rank 501-510
        "uma", "vuna", "ngazi", "mpwa", "kiwiko", "kidevu", "baiskeli", "taya", "sindano", "kifundo",
        -- Rank 511-520
        "beri", "shavu", "butu", "mboga", "mtungi", "gunia", "mshumaa", "kijiko", "paji", "kiwiko",
        -- Rank 521-530
        "kisigino", "mpwa", "shoka", "kovu", "mdudu", "kiu", "tochi", "glavu", "mkuki", "suruali",
        -- Rank 531-540
        "kinywaji", "jirani", "upweke", "uyoga", "karaha", "ndugu", "soksi", "ubavu", "sepetu", "panda",
        -- Rank 541-543
        "bendeji", "chubuko", "kitovu",
    },

    -- ========================================================================
    -- CULTURAL BLOCK -- see TAZC_Palette_French for full schema docs. Swahili;
    -- multi-word l2 phrases are fine (the cultural pass substitutes whole phrases).
    -- ========================================================================
    cultural = {
        { en = "No worries, there is no problem at all", l2 = "hakuna matata",  tags = {} },
        { en = "Welcome, please come in my friend",      l2 = "karibu",         tags = {"greeting"} },
        { en = "Slowly slowly, take it nice and easy",   l2 = "pole pole",      tags = {} },
        { en = "Thank you very much, I am grateful",     l2 = "asante sana",    tags = {"courtesy"} },
        { en = "Goodbye, farewell to you for now",       l2 = "kwa heri",       tags = {"farewell"} },
        { en = "Have a safe journey, travel well",       l2 = "safari njema",   tags = {"farewell"} },
    },
}

-- Self-register with the language system.
require("TAZC_LangRegistry").register("bantu", bantu)

return bantu
