-- TAZC_Babble palette: Persian
-- Iranian family -- the broad, "dynastic" Persian palette. DYNASTIC, NOT CADET:
-- one palette stands in for the Iranian branch (Persian/Farsi, Dari, Tajik). A
-- Western ear doesn't reliably split them, so players who want to voice a
-- specific variety use this palette and self-identify their nation in RP; the
-- babble stays at the family level. Tehrani Persian is the base.
--
-- Phonological signature: the kh/gh/q gutturals and the zh fricative (the 's' in
-- "measure"), the long "aa" (â) vowel, the ow/ey diphthongs, and the silent-h
-- "-eh" endings (khaneh = house, baleh = yes). No initial consonant clusters
-- (Persian breaks them with a helping vowel); modest final clusters (-sht, -rd).
--
-- Orthography: romanized ASCII in a consistent academic-lite scheme -- NO
-- Perso-Arabic script, NO diacritics, NO multibyte. Long a is written "aa"; the
-- ee/oo long vowels are "i"/"u"; kh/gh/zh/ch/sh are the digraph tells. Verbs are
-- cited in the infinitive (-tan/-dan): raftan = to go, khordan = to eat.

local persian = {
    name   = "Persian",
    family = "iranian",

    -- Tuning dials -- see TAZC_Babble.lua header. Onset-heavy CV(C) syllables, no
    -- initial clusters, occasional final clusters via the coda pool; one featured
    -- tell per utterance.
    tuning = {
        lettersPerSyllable     = 3,
        onsetChance            = 0.9,   -- Persian syllables almost always take an onset
        midCodaChance          = 0.35,
        endingPoolChance       = 0.4,
        functionWordChance     = 0.4,
        elisionPrefixChance    = 0,     -- Persian-specific: no elisions
        signatureBoostWeight   = 2,
        featuredSignatureCount = 1,
    },

    onsets = {
        -- Single consonants only (no initial clusters in Persian).
        "b", "p", "t", "s", "j", "ch", "h", "kh", "d", "z", "r", "zh",
        "sh", "gh", "f", "q", "k", "g", "l", "m", "n", "v", "y",
    },

    nuclei = {
        -- Short a/e/o weighted heavy; long aa/i/u are the tells; ow/ey diphthongs.
        "a", "a", "e", "e", "o", "o", "aa", "aa", "i", "i", "u", "ey", "ow",
    },

    codas = {
        -- Final single consonants plus a few Persian final clusters (-st/-ng/-rd);
        -- empty for open syllables.
        "", "", "n", "r", "sh", "m", "d", "kh", "z", "l", "t", "g", "st", "ng", "rd",
    },

    functionWords = {
        -- Ultra-common Persian particles/pronouns/conjunctions.
        "va", "ke", "ba", "az", "be", "dar", "man", "to", "u", "in",
        "an", "ra", "ham", "na", "baleh", "che", "ki", "hameh",
    },

    -- Hesitation fillers (see TAZC_Palette_Turkish for schema docs).
    fillers = {
        "khob",          -- "khob: well / ok" (stalling)
        "yani",          -- "yani: I mean / that is"
        "chiz",          -- "chiz...: thingy / uh" (word-search filler)
    },

    -- Signature set. The gutturals and the long vowels are the tells.
    signatureSet = {
        persianGutturals = { category = "onset",   elements = {"kh", "gh", "q", "zh"} },
        longVowels       = { category = "nucleus", elements = {"aa", "i", "u"} },
    },

    -- Mishearing rules (babble-resolve). Gutturals flatten and the long vowels
    -- shorten in a non-native ear. DRAFT -- for review. See docs/BABBLE_RESOLVE.md.
    mishearing = {
        { "kh", "h" }, { "gh", "g" }, { "q", "k" }, { "zh", "j" },  -- gutturals/fricative flatten
        { "aa", "a" }, { "ey", "e" }, { "ow", "o" },                -- long vowels / diphthongs shorten
    },

    -- Output guard: real Persian vulgarities generated babble must never land on.
    -- Whole-word, lowercase (romanized). DRAFT -- native review. See
    -- TAZC_Palette_Turkish for docs.
    babbleBlocklist = {
        "kir", "kos", "koskesh", "koskes", "jende", "jakesh",
        "ghahbe", "madarjende", "kuni", "goh",
    },

    -- ====================================================================
    -- INTEGRATION-LAYER DATA (optional, ignored by TAZC_Babble engine)
    -- ====================================================================

    -- concept-keyed lex sourced from data/forms.tsv (the persian column) via
    -- devtools/generate_palette_forms.py. Tehrani Persian, romanized: verbs in
    -- the infinitive (-tan/-dan); nouns/adjectives base. DRAFTS pending native-
    -- speaker review (flagged in the TSV note column). Romanization homophones
    -- are expected and noted in the forms.
    lex = require("TAZC_PaletteFormsData").persian,

    -- Zipf frequency order. Generated by devtools/generate_rankings.py; Persian
    -- never shipped, so all forms ride the baseline-less English-frequency path.
    -- Regenerate after editing forms.tsv; do NOT hand-edit.
    zipf = {
        -- GENERATED by devtools/generate_rankings.py -- do NOT hand-edit.
        -- Order: frozen 8.16.1 baseline + frequency-anchored insertions
        -- (see generator docstring). Regenerate after editing forms.tsv.
        -- Rank 1-10
        "daakhel", "man", "aan", "to", "in", "na", "maa", "hameh", "aanhaa", "yek",
        -- Rank 11-20
        "quti", "baalaa", "birun", "chi", "key", "na", "ki", "now", "chetor", "alaan",
        -- Rank 21-30
        "digar", "khub", "baad", "avval", "daanestan", "didan", "do", "saakhtan", "andishidan", "sepas",
        -- Rank 31-40
        "posht", "khaastan", "raftan", "saalem", "kojaa", "niaaz", "raast", "kaar", "saal", "ruz",
        -- Rank 41-50
        "qabl", "cheraa", "gereftan", "ziyaad", "goftan", "paayin", "eshq", "mard", "khaaneh", "deraaz",
        -- Rank 51-60
        "negaristan", "chizi", "estefaadeh", "yeksaan", "aamadan", "seh", "yaaftan", "komak", "kohneh", "baazi",
        -- Rank 61-70
        "daadan", "khaaneh", "dobaareh", "namaayaandan", "bozorg", "negahdaashtan", "faamil", "lotfan", "kasi", "chap",
        -- Rank 71-80
        "naam", "shab", "baazidan", "kam", "motefaavet", "baalaa", "shoru", "hafteh", "harchi", "aadam",
        -- Rank 81-90
        "emruz", "hamechi", "por", "zistan", "khaandan", "bad", "chahaar", "sakht", "goftan", "istaadan",
        -- Rank 91-100
        "aab", "sar", "kuchak", "sefid", "dur", "shoghl", "taraf", "kushidan", "baleh", "davidan",
        -- Rank 101-110
        "goshudan", "fasl", "sepaas", "siyaah", "maashin", "chehreh", "panj", "shaayad", "daastaan", "omid",
        -- Rank 111-120
        "mohem", "ketaab", "zud", "javaan", "nesf", "dast", "badan", "ghazaa", "jonub", "otaaq",
        -- Rank 121-130
        "bordan", "ghalat", "dust", "zadan", "fahmidan", "bastan", "jonbidan", "zan", "porsidan", "dir",
        -- Rank 131-140
        "shomaal", "arreh", "nur", "sabok", "sobh", "maandan", "qermez", "zud", "qalb", "bacheh",
        -- Rank 141-150
        "aatash", "posht", "saakhtemaan", "aasaan", "nazdik", "barnaameh", "shesh", "gharb", "jelow", "aamaadeh",
        -- Rank 151-160
        "pesar", "aavardan", "barkhordan", "nozaad", "pedar", "aahang", "maah", "boridan", "mazraeh", "maadar",
        -- Rank 161-170
        "jaaddeh", "shahr", "jangidan", "shenidan", "qeymat", "esteraahat", "taabestaan", "zan", "qavi", "chomaaq",
        -- Rank 171-180
        "taqsim", "mordeh", "shodan", "gereftan", "setaareh", "shekastan", "saaat", "vasat", "bebakhshid", "javaab",
        -- Rank 181-190
        "aamukhtan", "tanhaa", "kelisaa", "sharq", "garm", "istaadan", "aabi", "raandan", "khordan", "oftaadan",
        -- Rank 191-200
        "tond", "sabz", "etemaad", "kelid", "tejaarat", "baraadar", "fenjaan", "ferestaadan", "khun", "sag",
        -- Rank 201-210
        "roghan", "koshtan", "faqir", "pushaandan", "dar", "mu", "haft", "saadeh", "dokhtar", "mordan",
        -- Rank 211-220
        "kaaghaz", "imen", "khaak", "faraamushidan", "daryaa", "khaabidan", "dah", "jabeh", "saakhtan", "taarik",
        -- Rank 221-230
        "divaar", "dard", "rudkhaaneh", "neveshtan", "sard", "hasht", "cheshm", "solh", "andukhtan", "fardaa",
        -- Rank 231-240
        "qahvei", "raadyo", "showhar", "yakh", "tamiz", "khorshid", "tofang", "sangin", "jostan", "tars",
        -- Rank 241-250
        "rahbar", "naameh", "maaddeh", "hichkas", "khaahar", "maghz", "kaf", "hich", "bahaar", "pushidan",
        -- Rank 251-260
        "royaa", "tamaam", "shaans", "servatmand", "pust", "basaavidan", "diruz", "nushidan", "maahi", "ruidan",
        -- Rank 261-270
        "neshastan", "bordan", "giyaah", "zemestaan", "bimaar", "gereftan", "paa", "noh", "qahveh", "asr",
        -- Rank 271-280
        "shisheh", "aahesteh", "derakht", "paayin", "motor", "ghamgin", "baad", "negaraani", "shomordan", "daryaacheh",
        -- Rank 281-290
        "dahaan", "andaakhtan", "felez", "keshidan", "heyvaan", "sang", "panjereh", "kif", "urdugaah", "gorbeh",
        -- Rank 291-300
        "tasmim", "hedyeh", "chub", "pol", "baagh", "zendeh", "asb", "naqsheh", "tur", "khodro",
        -- Rank 301-310
        "gusheh", "mazraeh", "paridan", "taajob", "khoshk", "labeh", "jaraahat", "baazu", "daaru", "kuh",
        -- Rank 311-320
        "cheshidan", "chaay", "sukht", "salaam", "aasemaan", "qaayeq", "sad", "raah", "qol", "baaraan",
        -- Rank 321-330
        "khasteh", "doshman", "jangal", "maah", "paridan", "zard", "narm", "dud", "aamuzaandan", "suraakh",
        -- Rank 331-340
        "paa", "shir", "barf", "zaif", "zanjir", "pokhtan", "aashpazkhaaneh", "saaket", "ajib", "kaamyun",
        -- Rank 341-350
        "parandeh", "kaaseh", "morgh", "gusht", "gardan", "piraahan", "naaranji", "mashrub", "namak", "movaazeb",
        -- Rank 351-360
        "khatar", "khaali", "mehmaan", "botri", "panir", "miveh", "abzaar", "kasif", "shaadi", "sedaa",
        -- Rank 361-370
        "boshqaab", "aasudegi", "berenj", "baam", "sharm", "aaraam", "nehoftan", "aslaheh", "khis", "sukhtan",
        -- Rank 371-380
        "kolaah", "boland", "sineh", "surati", "qofl", "bini", "pelaastik", "bastan", "naan", "bardaashtan",
        -- Rank 381-390
        "shaaneh", "charkh", "buteh", "buidan", "angosht", "khaakestari", "tiz", "ostokhaan", "lebaas", "darvaazeh",
        -- Rank 391-400
        "abr", "tokhm", "shostan", "gorosneh", "amu", "maaseh", "nakh", "saaat", "gush", "khashm",
        -- Rank 401-410
        "kamarband", "gol", "medeh", "pesaramu", "gard", "chaaqu", "risheh", "dozdidan", "qaablameh", "taabeh",
        -- Rank 411-420
        "chaman", "asal", "qollaab", "bazr", "shamshir", "zabaan", "paalto", "aabmiveh", "pestaan", "charm",
        -- Rank 421-430
        "gorg", "ofunat", "zaanu", "daam", "banafsh", "gazidan", "maask", "nimeshab", "kamaan", "khodaahaafez",
        -- Rank 431-440
        "separ", "galu", "gharibeh", "paayiz", "goluleh", "chidan", "pedarbozorg", "kafsh", "zakhm", "kaf",
        -- Rank 441-450
        "laastik", "maar", "kandan", "tab", "barg", "nardeh", "naakhon", "mikh", "ghaar", "gusht",
        -- Rank 451-460
        "chakmeh", "sardargomi", "gusfand", "ghalleh", "boshkeh", "mush", "khaakestar", "khaaleh", "chakosh", "mahsul",
        -- Rank 461-470
        "sup", "gaav", "maadarbozorg", "khuk", "pelleh", "tir", "lab", "gel", "aahu", "zohr",
        -- Rank 471-480
        "shekam", "riyeh", "gham", "zahr", "dandaan", "sabad", "patu", "satl", "tanaab", "cheraagh",
        -- Rank 481-490
        "aajil", "paarcheh", "zarf", "changaal", "bardaasht", "nardebaan", "baraadarzaadeh", "shast", "moch", "chaaneh",
        -- Rank 491-500
        "docharkheh", "fak", "suzan", "quzak", "tut", "guneh", "kond", "sabzi", "kuze", "guni",
        -- Rank 501-510
        "sham", "qaashoq", "pishaani", "aarenj", "paashneh", "khaaharzaadeh", "tabar", "hashareh", "teshneh", "mashal",
        -- Rank 511-520
        "dastkash", "neyzeh", "shalvaar", "nushidani", "hamsaayeh", "tanhaai", "qaarch", "enzejaar", "juraab", "dandeh",
        -- Rank 521-525
        "bil", "kaashtan", "zakhmband", "kabudi", "naaf",
    },

    -- ========================================================================
    -- CULTURAL BLOCK -- see TAZC_Palette_French for full schema docs. Romanized;
    -- multi-word l2 phrases are fine (the cultural pass substitutes whole
    -- phrases, not single tokens). Persian taarof flavor.
    -- ========================================================================
    cultural = {
        { en = "Hello, peace be upon you",            l2 = "salaam",              tags = {"greeting"} },
        { en = "Thank you very much indeed",          l2 = "kheyli mamnun",       tags = {} },
        { en = "May your hand not ache, thank you",   l2 = "dastet dard nakoneh", tags = {} },
        { en = "Go safely with God, farewell",        l2 = "khodaa haafez",       tags = {"farewell"} },
        { en = "Please, go ahead, be my guest",       l2 = "befarmaa",            tags = {} },
        { en = "I would give my life for you, dear",  l2 = "ghorbaanet beram",    tags = {} },
    },
}

-- Self-register with the language system.
require("TAZC_LangRegistry").register("persian", persian)

return persian
