-- TAZC_Babble palette: Italian
-- Romance family. Phonological signature: near-universal vowel endings
-- (-o/-a/-e/-i), the gl/gn palatals and sc(e/i) sibilant, and the Latinate
-- suffix tail (-zione/-mente/-tore). family = "romance", so the cross-language
-- Connection bonus links Italian with French and Spanish.
--
-- Identity: standard Italian. Orthography keeps the final-stress grave/acute
-- accents (a-grave, e-grave, o-grave ...), byte-escaped (\NNN) like the French
-- palette. Geminate note: true intervocalic double consonants (bello, tutto,
-- pizza, ragazzo) are a strong Italian tell but the mora-independent engine
-- cannot force a clean intervocalic geminate (same limit as Japonic) -- they
-- live in the acquired lex and in the mishearing rules, not in generated babble.

local italian = {
    name   = "Italian",
    family = "romance",

    -- Tuning dials -- see TAZC_Babble.lua header. Italian words almost always end
    -- in a vowel, so codas are weighted heavily empty and the suffix pool
    -- (-zione/-mente) is itself vowel-final; featuredSignatureCount 1 + a gentle
    -- boost keeps the tells sprinkled.
    tuning = {
        lettersPerSyllable     = 3,
        onsetChance            = 0.72,
        midCodaChance          = 0.22,
        endingPoolChance       = 0.22,
        functionWordChance     = 0.4,
        elisionPrefixChance    = 0,     -- Italian elision (l'acqua) left off for clean single tokens
        signatureBoostWeight   = 2,
        featuredSignatureCount = 1,
    },

    onsets = {
        "b", "c", "d", "f", "g", "l", "m", "n", "p", "r", "s", "t", "v", "z",
        "gl", "gn", "sc",                            -- gli/gn palatals, sc(e/i) sibilant
        "pr", "tr", "br", "cr", "gr", "fr", "pl", "str",  -- clusters incl. s+stop (strada)
    },

    nuclei = {
        -- Pure vowels dominate and carry the vowel endings; a/e/o 4x, i 3x, u 2x.
        "a", "a", "a", "a", "e", "e", "e", "e", "i", "i", "i", "o", "o", "o", "o", "u", "u",
        -- Common diphthongs (piano, ieri, uomo, buono).
        "ia", "ie", "io", "uo",
        -- Final-stress accents (a-grave, e-grave, o-grave).
        "\195\160", "\195\168", "\195\178",
    },

    codas = {
        -- Italian words nearly always end in a vowel; only a few function words
        -- and loans close with -n, so codas are weighted heavily empty.
        "", "", "", "", "", "n",
    },

    functionWords = {
        "il", "lo", "la", "le", "un", "una", "di", "del", "e", "che",
        "in", "con", "per", "non", "si", "ci", "da", "al", "ma", "gli",
    },

    -- Hesitation fillers (see TAZC_Palette_Turkish for schema docs).
    fillers = {
        "allora",        -- "so / well then" -- the universal Italian filler
        "ecco",          -- "here / there we go"
        "cio\195\168",   -- "cioè: that is / I mean"
    },

    -- Signature set. The coda-category suffix elements are consonant-initial and
    -- themselves vowel-final, so they attach cleanly and preserve the vowel
    -- ending (na + zione -> "nazione", a + mente -> "amente").
    signatureSet = {
        latinateSuffixes = { category = "coda",  elements = {"zione", "mente", "tore", "ssimo"} },
        palatals         = { category = "onset", elements = {"gl", "gn", "sc"} },
    },

    -- Mishearing rules (babble-resolve). Palatals flatten, geminates simplify,
    -- final-stress accents drop. DRAFT -- for review. See docs/BABBLE_RESOLVE.md.
    mishearing = {
        { "gl", "l" }, { "gn", "n" }, { "sc", "s" },                       -- palatals flatten
        { "zz", "z" }, { "tt", "t" }, { "cc", "c" }, { "ll", "l" }, { "ss", "s" }, { "pp", "p" },  -- de-geminate
        { "\195\160", "a" }, { "\195\168", "e" }, { "\195\169", "e" }, { "\195\172", "i" },
        { "\195\178", "o" }, { "\195\179", "o" }, { "\195\185", "u" },
    },

    -- Output guard: real Italian vulgarities generated babble must never land on.
    -- Whole-word, lowercase. See TAZC_Palette_Turkish for schema docs.
    babbleBlocklist = {
        "cazzo", "merda", "stronzo", "puttana", "culo", "figa",
        "minchia", "troia", "coglione", "porca",
    },

    -- ====================================================================
    -- INTEGRATION-LAYER DATA (optional, ignored by TAZC_Babble engine)
    -- ====================================================================

    -- concept-keyed lex sourced from data/forms.tsv (the italian column) via
    -- devtools/generate_palette_forms.py. Standard Italian: verbs in the
    -- infinitive (-are/-ere/-ire); nouns singular; adjectives masculine singular.
    -- DRAFTS pending native-speaker review (flagged in the TSV note column).
    lex = require("TAZC_PaletteFormsData").italian,

    -- Zipf frequency order. Generated by devtools/generate_rankings.py; Italian
    -- never shipped, so all forms flow through the baseline-less English-frequency
    -- path. Regenerate after editing forms.tsv; do NOT hand-edit.
    zipf = {
        -- GENERATED by devtools/generate_rankings.py -- do NOT hand-edit.
        -- Order: frozen 8.16.1 baseline + frequency-anchored insertions
        -- (see generator docstring). Regenerate after editing forms.tsv.
        -- Rank 1-10
        "dentro", "io", "quello", "tu", "questo", "non", "noi", "tutto", "loro", "uno",
        -- Rank 11-20
        "lattina", "su", "fuori", "cosa", "quando", "no", "chi", "nuovo", "come", "adesso",
        -- Rank 21-30
        "altro", "buono", "dopo", "primo", "sapere", "vedere", "due", "fare", "pensare", "allora",
        -- Rank 31-40
        "schiena", "volere", "andare", "sano", "dove", "bisogno", "destra", "lavorare", "anno", "giorno",
        -- Rank 41-50
        "prima", "perch\195\169", "prendere", "molto", "dire", "gi\195\185", "amore", "uomo", "casa", "lungo",
        -- Rank 51-60
        "guardare", "qualcosa", "usare", "stesso", "venire", "tre", "trovare", "aiuto", "vecchio", "gioco",
        -- Rank 61-70
        "dare", "casa", "ancora", "mostrare", "grande", "sentire", "tenere", "famiglia", "qualcuno", "sinistro",
        -- Rank 71-80
        "nome", "notte", "giocare", "poco", "diverso", "cima", "iniziare", "settimana", "qualsiasi", "persona",
        -- Rank 81-90
        "oggi", "tutto", "pieno", "vivere", "leggere", "cattivo", "quattro", "duro", "raccontare", "fermare",
        -- Rank 91-100
        "acqua", "testa", "piccolo", "bianco", "lontano", "lavoro", "lato", "provare", "s\195\172", "correre",
        -- Rank 101-110
        "aprire", "stagione", "grazie", "nero", "macchina", "faccia", "cinque", "forse", "storia", "speranza",
        -- Rank 111-120
        "importante", "libro", "presto", "giovane", "met\195\160", "mano", "corpo", "cibo", "sud", "stanza",
        -- Rank 121-130
        "vincere", "sbagliato", "ricordare", "amico", "colpire", "capire", "chiudere", "muovere", "aspettare", "donna",
        -- Rank 131-140
        "chiedere", "tardi", "nord", "sega", "luce", "leggero", "mattina", "restare", "rosso", "presto",
        -- Rank 141-150
        "cuore", "bambino", "fuoco", "dietro", "edificio", "facile", "vicino", "piano", "sei", "ovest",
        -- Rank 151-160
        "davanti", "pronto", "figlio", "portare", "incontrare", "neonato", "padre", "canzone", "mese", "tagliare",
        -- Rank 161-170
        "campo", "madre", "strada", "paese", "combattere", "sentire", "prezzo", "riposare", "estate", "moglie",
        -- Rank 171-180
        "forte", "mazza", "condividere", "morto", "succedere", "tenere", "stella", "rompere", "ora", "centro",
        -- Rank 181-190
        "scusa", "rispondere", "imparare", "solo", "chiesa", "est", "caldo", "seguire", "alzarsi", "blu",
        -- Rank 191-200
        "guidare", "mangiare", "cadere", "veloce", "verde", "fidarsi", "chiave", "scambiare", "fratello", "tazza",
        -- Rank 201-210
        "odiare", "mandare", "sangue", "cane", "olio", "uccidere", "povero", "coprire", "porta", "capelli",
        -- Rank 211-220
        "perdere", "sette", "semplice", "camminare", "figlia", "morire", "carta", "sicuro", "terra", "dimenticare",
        -- Rank 221-230
        "mare", "dormire", "dieci", "scatola", "costruire", "buio", "muro", "dolore", "fiume", "parlare",
        -- Rank 231-240
        "scrivere", "freddo", "otto", "occhio", "pace", "immagazzinare", "domani", "marrone", "radio", "marito",
        -- Rank 241-250
        "ghiaccio", "pulito", "sole", "pistola", "pesante", "cercare", "paura", "capo", "lettera", "materiale",
        -- Rank 251-260
        "nessuno", "sorella", "cervello", "pavimento", "niente", "primavera", "indossare", "sognare", "finire", "fortuna",
        -- Rank 261-270
        "ricco", "pelle", "toccare", "ieri", "bere", "pesce", "crescere", "sedersi", "portare", "pianta",
        -- Rank 271-280
        "inverno", "malato", "acchiappare", "piede", "nove", "caff\195\168", "sera", "vetro", "lento", "albero",
        -- Rank 281-290
        "fondo", "motore", "sdraiarsi", "tristezza", "vento", "preoccupazione", "contare", "lago", "bocca", "lanciare",
        -- Rank 291-300
        "metallo", "tirare", "spingere", "animale", "entrare", "pietra", "finestra", "borsa", "accampamento", "gatto",
        -- Rank 301-310
        "decidere", "regalo", "legno", "ponte", "orto", "vivo", "cavallo", "mappa", "rete", "veicolo",
        -- Rank 311-320
        "svegliarsi", "angolo", "fattoria", "riparare", "volare", "sorpresa", "secco", "bordo", "lesione", "braccio",
        -- Rank 321-330
        "medicina", "montagna", "sparare", "assaggiare", "t\195\168", "carburante", "ciao", "cielo", "barca", "cento",
        -- Rank 331-340
        "sentiero", "promettere", "pioggia", "stanco", "nemico", "bosco", "luna", "saltare", "giallo", "morbido",
        -- Rank 341-350
        "fumo", "insegnare", "buco", "gamba", "latte", "neve", "debole", "catena", "cucinare", "cucina",
        -- Rank 351-360
        "silenzioso", "strano", "camion", "uccello", "ciotola", "gallina", "carne", "collo", "camicia", "arancione",
        -- Rank 361-370
        "alcol", "sale", "attento", "pericolo", "vuoto", "ospite", "bottiglia", "formaggio", "frutta", "attrezzo",
        -- Rank 371-380
        "sporco", "gioia", "rumore", "piatto", "sollievo", "riso", "tetto", "vergogna", "calmo", "nascondere",
        -- Rank 381-390
        "arma", "bagnato", "bruciare", "cappello", "rumoroso", "petto", "rosa", "serratura", "naso", "plastica",
        -- Rank 391-400
        "legare", "pane", "sollevare", "spalla", "ruota", "cespuglio", "cacciare", "annusare", "dito", "grigio",
        -- Rank 401-410
        "affilato", "osso", "vestito", "cancello", "nuvola", "uovo", "lavare", "affamato", "zio", "sabbia",
        -- Rank 411-420
        "filo", "orologio", "orecchio", "rabbia", "cintura", "fiore", "stomaco", "cugino", "polvere", "coltello",
        -- Rank 421-430
        "radice", "rubare", "pentola", "padella", "erba", "miele", "gancio", "seme", "spada", "lingua",
        -- Rank 431-440
        "cappotto", "succo", "seno", "uscire", "cuoio", "lupo", "infezione", "ginocchio", "trappola", "viola",
        -- Rank 441-450
        "mordere", "maschera", "mezzanotte", "arco", "arrivederci", "scudo", "gola", "sconosciuto", "erbaccia", "autunno",
        -- Rank 451-460
        "respirare", "proiettile", "raccogliere", "nonno", "scarpa", "ferita", "palmo", "gomma", "serpente", "arrampicarsi",
        -- Rank 461-470
        "scavare", "febbre", "foglia", "recinzione", "unghia", "chiodo", "nuotare", "grotta", "carne", "stivale",
        -- Rank 471-480
        "confusione", "pecora", "grano", "barile", "ratto", "cenere", "zia", "martello", "coltura", "zuppa",
        -- Rank 481-490
        "mucca", "nonna", "maiale", "scala", "freccia", "labbro", "fango", "cervo", "guarire", "mezzogiorno",
        -- Rank 491-500
        "pancia", "polmone", "lutto", "veleno", "dente", "cesto", "coperta", "secchio", "dito", "corda",
        -- Rank 501-510
        "gridare", "lampada", "noce", "stoffa", "contenitore", "forchetta", "raccogliere", "scala", "nipote", "pollice",
        -- Rank 511-520
        "polso", "mento", "bicicletta", "mascella", "ago", "caviglia", "bacca", "guancia", "spuntato", "verdura",
        -- Rank 521-530
        "barattolo", "sacco", "candela", "cucchiaio", "fronte", "gomito", "tallone", "nipote", "ascia", "cicatrice",
        -- Rank 531-540
        "insetto", "assetato", "torcia", "guanto", "sanguinare", "lancia", "pantalone", "bevanda", "vicino", "solitudine",
        -- Rank 541-550
        "fungo", "disgusto", "fratello", "calzino", "costola", "pala", "seminare", "benda", "livido", "ombelico",
    },

    -- ========================================================================
    -- CULTURAL BLOCK -- see TAZC_Palette_French for full schema docs.
    -- ========================================================================
    cultural = {
        { en = "Good luck out there, break a leg",     l2 = "In bocca al lupo",        tags = {"encouragement"} },
        { en = "It is not a problem at all",           l2 = "Non c'\195\168 problema", tags = {} },
        { en = "Little by little, take it slow",       l2 = "Piano piano",             tags = {} },
        { en = "Whatever will be, will be",            l2 = "Quel che sar\195\160 sar\195\160", tags = {} },
        { en = "Enjoy your meal, everyone",            l2 = "Buon appetito",           tags = {"meal"} },
        { en = "Let us go now, come on",               l2 = "Andiamo, dai",            tags = {"action"} },
    },
}

-- Self-register with the language system.
require("TAZC_LangRegistry").register("italian", italian)

return italian
