-- TAZC_Babble palette: Korean
-- Koreanic family. A STANDALONE palette (not folded under Japonic): Korean has
-- strong RP/gaming demand and a distinct sound -- the three-way stops, the eo/eu
-- vowels, and the batchim final consonants read as clearly Korean, not Japanese.
--
-- Phonological signature: the eo (ㅓ) and eu (ㅡ) vowels that no other palette
-- here uses, the plain/tense/aspirated stop triads (g/kk/k, d/tt/t, b/pp/p,
-- j/jj/ch), the clean (C)V(C) syllable blocks, and the -ng/-n/-l/-k batchim
-- (final-consonant) endings.
--
-- Orthography: standard Revised Romanization of Korean (RR), ASCII-clean -- no
-- multibyte, no tone/length marks. eo/eu/ae are digraph vowels; the tense stops
-- are doubled (kk/tt/pp/ss/jj).

local korean = {
    name   = "Korean",
    family = "koreanic",

    -- Tuning dials -- see TAZC_Babble.lua header. Clean CVC blocks with frequent
    -- batchim final consonants; one featured tell per utterance.
    tuning = {
        lettersPerSyllable     = 3,
        onsetChance            = 0.85,
        midCodaChance          = 0.4,
        endingPoolChance       = 0.4,
        functionWordChance     = 0.4,
        elisionPrefixChance    = 0,     -- Korean-specific: no elisions
        signatureBoostWeight   = 2,
        featuredSignatureCount = 1,
    },

    onsets = {
        -- RR three-way: plain g/d/b/j, tense kk/tt/pp/jj/ss, aspirated k/t/p/ch.
        "g", "k", "kk", "n", "d", "t", "tt", "r", "m", "b", "p", "pp",
        "s", "ss", "j", "ch", "jj", "h",
    },

    nuclei = {
        -- eo/eu/ae are the Korean vowel tells (weighted alongside a).
        "a", "a", "eo", "eo", "o", "u", "eu", "eu", "i", "e", "ae",
        -- y-/w- glide vowels.
        "ya", "yeo", "yo", "yu", "wa", "wo", "ui",
    },

    codas = {
        -- Batchim: only 7 released finals (k/n/t/l/m/p/ng); -ng/-n/-l are common,
        -- plus empty for open syllables.
        "", "", "ng", "n", "l", "k", "m", "p", "t",
    },

    functionWords = {
        -- Particles + pronouns/demonstratives.
        "eun", "neun", "i", "ga", "eul", "reul", "e", "do", "man", "wa",
        "gwa", "na", "neo", "geu", "ne", "yo", "hago", "seo", "ui",
    },

    -- Hesitation fillers (see TAZC_Palette_Turkish for schema docs).
    fillers = {
        "eum",           -- "eum: uh / mm" -- the universal filler
        "geu",           -- "geu...: that / uh" (stalling)
        "jeogi",         -- "jeogi: um / excuse me"
    },

    -- Signature set. The eo/eu vowels, the tense/aspirated stops, and the batchim
    -- finals are the tells.
    signatureSet = {
        koreanVowels  = { category = "nucleus", elements = {"eo", "eu", "ae"} },
        tenseAspirate = { category = "onset",   elements = {"kk", "tt", "pp", "ss", "jj", "k", "t", "p", "ch"} },
        batchimFinals = { category = "coda",    elements = {"ng", "n", "l"} },
    },

    -- Mishearing rules (babble-resolve). Tense/aspirated stops flatten to plain,
    -- the eo/eu vowels round toward o/u, -ng collapses to -n. DRAFT -- for review.
    -- See docs/BABBLE_RESOLVE.md.
    mishearing = {
        { "kk", "k" }, { "tt", "t" }, { "pp", "p" }, { "ss", "s" }, { "jj", "j" },  -- tense -> plain
        { "eo", "o" }, { "eu", "u" }, { "ae", "e" },                                 -- vowels round/simplify
        { "ng", "n" }, { "ch", "j" },                                                -- velar nasal, aspirate
    },

    -- Output guard: real Korean vulgarities generated babble must never land on.
    -- Whole-word, lowercase (RR). See TAZC_Palette_Turkish for docs.
    babbleBlocklist = {
        "shibal", "ssibal", "gaesaekki", "byeongsin", "jaji", "boji",
        "nyeon", "jotgat", "gaesekki",
    },

    -- ====================================================================
    -- INTEGRATION-LAYER DATA (optional, ignored by TAZC_Babble engine)
    -- ====================================================================

    -- concept-keyed lex sourced from data/forms.tsv (the korean column) via
    -- devtools/generate_palette_forms.py. Standard Korean in RR: verbs in the
    -- dictionary -da form; nouns/adjectives base. DRAFTS pending native-speaker
    -- review (flagged in the TSV note column).
    lex = require("TAZC_PaletteFormsData").korean,

    -- Zipf frequency order. Generated by devtools/generate_rankings.py; Korean
    -- never shipped, so all forms ride the baseline-less English-frequency path.
    -- Regenerate after editing forms.tsv; do NOT hand-edit.
    zipf = {
        -- GENERATED by devtools/generate_rankings.py -- do NOT hand-edit.
        -- Order: frozen 8.16.1 baseline + frequency-anchored insertions
        -- (see generator docstring). Regenerate after editing forms.tsv.
        -- Rank 1-10
        "an", "na", "jeogeot", "neo", "igeot", "an", "uri", "modu", "geudeul", "hana",
        -- Rank 11-20
        "kkangtong", "wi", "bak", "mueot", "eonje", "ani", "nugu", "saeropda", "eotteoke", "jigeum",
        -- Rank 21-30
        "dareun", "jota", "hu", "cheotjjae", "alda", "boda", "dul", "mandeulda", "saenggakhada", "geuttae",
        -- Rank 31-40
        "deung", "wonhada", "gada", "geonganghada", "eodi", "piryohada", "oreunjjok", "ilhada", "nyeon", "nat",
        -- Rank 41-50
        "jeon", "wae", "gajida", "manta", "malhada", "arae", "sarang", "namja", "jip", "gilda",
        -- Rank 51-60
        "boda", "mwonga", "sayonghada", "gatda", "oda", "set", "chatda", "dopda", "oraedoeda", "nori",
        -- Rank 61-70
        "juda", "jip", "dasi", "boyeojuda", "keuda", "neukkida", "gajida", "gajok", "jebal", "nugunga",
        -- Rank 71-80
        "oenjjok", "ireum", "bam", "nolda", "jeokda", "dareuda", "kkokdaegi", "sijakhada", "ju", "amugeona",
        -- Rank 81-90
        "saram", "oneul", "jeonbu", "gadeuk", "salda", "ikda", "nappeuda", "net", "dandanhada", "malhada",
        -- Rank 91-100
        "meomchuda", "mul", "meori", "jakda", "hayata", "meolda", "il", "yeop", "sidohada", "ne",
        -- Rank 101-110
        "dallida", "yeolda", "gyejeol", "gomapda", "geomda", "jadongcha", "eolgul", "daseot", "ama", "iyagi",
        -- Rank 111-120
        "huimang", "jungyohada", "chaek", "iljjik", "eorida", "ban", "son", "mom", "eumsik", "namjjok",
        -- Rank 121-130
        "bang", "igida", "teullida", "gieokhada", "chingu", "ttaerida", "ihaehada", "datda", "umjigida", "gidarida",
        -- Rank 131-140
        "yeoja", "mutda", "neutda", "bukjjok", "top", "bit", "gabyeopda", "achim", "meomulda", "ppalgang",
        -- Rank 141-150
        "got", "simjang", "ai", "bul", "dwi", "geonmul", "swipda", "gakkapda", "gyehoek", "yeoseot",
        -- Rank 151-160
        "seojjok", "ap", "junbidoeda", "adeul", "gajyeooda", "mannada", "agi", "abeoji", "norae", "dal",
        -- Rank 161-170
        "jareuda", "deulpan", "eomeoni", "doro", "maeul", "ssauda", "deutda", "gagyeok", "swida", "yeoreum",
        -- Rank 171-180
        "anae", "ganghada", "mongdungi", "nanuda", "jugeun", "saenggida", "japda", "byeol", "busuda", "sigan",
        -- Rank 181-190
        "gaunde", "mianhada", "daedaphada", "baeuda", "honja", "gyohoe", "dongjjok", "tteugeopda", "ttareuda", "seoda",
        -- Rank 191-200
        "parata", "unjeonhada", "meokda", "tteoreojida", "ppareuda", "chorok", "mitda", "yeolsoe", "georaehada", "hyeong",
        -- Rank 201-210
        "keop", "miwohada", "bonaeda", "pi", "gae", "gireum", "jugida", "gananhada", "deopda", "mun",
        -- Rank 211-220
        "meorikarak", "ilta", "ilgop", "gandanhada", "geotda", "ttal", "jukda", "jongi", "anjeonhada", "ttang",
        -- Rank 221-230
        "itda", "bada", "jada", "yeol", "sangja", "jitda", "eodupda", "byeok", "apeuda", "gang",
        -- Rank 231-240
        "malhada", "sseuda", "chupda", "yeodeol", "nun", "pyeonghwa", "jeojanghada", "naeil", "galsaek", "radio",
        -- Rank 241-250
        "nampyeon", "eoreum", "kkaekkeutada", "hae", "chong", "mugeopda", "chatda", "duryeoum", "daejang", "pyeonji",
        -- Rank 251-260
        "jaeryo", "amudo", "nuna", "noe", "badak", "eopda", "bom", "ipda", "kkum", "kkeutnaeda",
        -- Rank 261-270
        "un", "buyuhada", "pibu", "manjida", "eoje", "masida", "mulgogi", "jarada", "antta", "nareuda",
        -- Rank 271-280
        "singmul", "gyeoul", "apeuda", "japda", "bal", "ahop", "keopi", "jeonyeok", "yuri", "neurida",
        -- Rank 281-290
        "namu", "badak", "enjin", "nupda", "seulpeum", "baram", "geokjeonghada", "seda", "hosu", "ip",
        -- Rank 291-300
        "deonjida", "geumsok", "danggida", "milda", "dongmul", "deureogada", "dol", "changmun", "gabang", "yayeongji",
        -- Rank 301-310
        "goyangi", "gyeoljeonghada", "seonmul", "namu", "dari", "jeongwon", "salda", "mal", "jido", "geumul",
        -- Rank 311-320
        "charyang", "kkaeda", "guseok", "nongjang", "gochida", "nalda", "nollada", "mareuda", "gajangjari", "busang",
        -- Rank 321-330
        "pal", "yak", "san", "ssoda", "matboda", "cha", "yeollyo", "annyeong", "haneul", "bae",
        -- Rank 331-340
        "baek", "gil", "yaksokhada", "bi", "pigonhada", "jeok", "sup", "dal", "ttwida", "norata",
        -- Rank 341-350
        "budeureopda", "yeongi", "gareuchida", "gumeong", "dari", "uyu", "nun", "yakhada", "saseul", "yorihada",
        -- Rank 351-360
        "bueok", "joyonghada", "isanghada", "teureok", "sae", "geureut", "dak", "gogi", "mok", "syeocheu",
        -- Rank 361-370
        "juhwang", "sul", "sogeum", "josimhada", "wiheom", "bida", "sonnim", "byeong", "chijeu", "gwail",
        -- Rank 371-380
        "dogu", "deoreopda", "gippeum", "sori", "jeopsi", "ando", "ssal", "jibung", "bukkeureoum", "chabunhada",
        -- Rank 381-390
        "sumda", "mugi", "jeotda", "tada", "moja", "sikkeureopda", "gaseum", "bunhong", "jamulsoe", "ko",
        -- Rank 391-400
        "peullaseutik", "mukda", "ppang", "deulda", "eokkae", "bakwi", "deombul", "sanyanghada", "matda", "songarak",
        -- Rank 401-410
        "hoesaek", "nalkaropda", "ppyeo", "ot", "daemun", "gureum", "gyeran", "ssitda", "baegopeuda", "samchon",
        -- Rank 411-420
        "morae", "sil", "sigye", "gwi", "hwa", "belteu", "kkot", "wi", "sachon", "meonji",
        -- Rank 421-430
        "kal", "ppuri", "humchida", "naembi", "paen", "pul", "kkul", "galgori", "ssiat", "geom",
        -- Rank 431-440
        "hyeo", "oetu", "juseu", "gaseum", "nagada", "gajuk", "neukdae", "gamyeom", "mureup", "deot",
        -- Rank 441-450
        "bora", "mulda", "maseukeu", "jajeong", "hwal", "annyeong", "bangpae", "mokgumeong", "ibangin", "japcho",
        -- Rank 451-460
        "gaeul", "sumswida", "chongal", "moeuda", "harabeoji", "sinbal", "sangcheo", "sonbadak", "gomu", "baem",
        -- Rank 461-470
        "oreuda", "pada", "yeol", "ip", "ultari", "sontop", "mot", "suyeonghada", "donggul", "sal",
        -- Rank 471-480
        "bucheu", "hollan", "yang", "gongmul", "tong", "jwi", "jae", "imo", "mangchi", "jangmul",
        -- Rank 481-490
        "guk", "so", "halmeoni", "dwaeji", "gyedan", "hwasal", "ipsul", "jinheuk", "saseum", "chiryohada",
        -- Rank 491-500
        "jeongo", "bae", "pye", "bitan", "dok", "i", "baguni", "damyo", "yangdongi", "balgarak",
        -- Rank 501-510
        "batjul", "sorichida", "raempeu", "gyeongwa", "cheon", "yonggi", "pokeu", "suhwakhada", "sadari", "joka",
        -- Rank 511-520
        "eomji", "sonmok", "teok", "jajeongeo", "teok", "baneul", "balmok", "santtalgi", "ppyam", "mudida",
        -- Rank 521-530
        "chaeso", "hangari", "jaru", "yangcho", "sutgarak", "ima", "palkkumchi", "dwikkumchi", "joka", "dokki",
        -- Rank 531-540
        "hyungteo", "beolle", "mongmareuda", "hwaetbul", "janggap", "chulhyeolhada", "chang", "baji", "eumryo", "iut",
        -- Rank 541-550
        "oeroum", "beoseot", "hyeomo", "hyeongje", "yangmal", "galbi", "sap", "simda", "bungdae", "meong",
        -- Rank 551-551
        "baekkop",
    },

    -- ========================================================================
    -- CULTURAL BLOCK -- see TAZC_Palette_French for full schema docs. RR; multi-word
    -- l2 phrases are fine (the cultural pass substitutes whole phrases).
    -- ========================================================================
    cultural = {
        { en = "Hello there, greetings to you",         l2 = "annyeong haseyo",     tags = {"greeting"} },
        { en = "It is okay, no problem at all",         l2 = "gwaenchanhayo",       tags = {} },
        { en = "You can do it, keep going strong",      l2 = "hwaiting",            tags = {"encouragement"} },
        { en = "Go well, take care and goodbye",        l2 = "jal gayo",            tags = {"farewell"} },
        { en = "Have you eaten yet, my friend",         l2 = "bap meogeosseoyo",    tags = {"greeting"} },
        { en = "Oh dear, oh my goodness me",            l2 = "aigo",                tags = {} },
    },
}

-- Self-register with the language system.
require("TAZC_LangRegistry").register("korean", korean)

return korean
